export const elements = {
  logInn: document.getElementById("logg-inn"),
  gameify: document.getElementById("game"),
  startGame: document.getElementById("start-game"),
  inventory: document.querySelector("#menu-card"),
  attack: document.querySelector("#attack"),
  escape: document.querySelector("#run"),
  healed: document.querySelector("#heal"),
  goForward: document.querySelector("#forth"),
  act: document.querySelector("#actions"),
  invBtn: document.querySelector("#inv-btn"),
  closeBtn: document.querySelector("#close-btn"),
  statLevel: document.querySelector("#statlvl"),
  statInv: document.querySelector("#stats-el"),
  bossFight: document.querySelector("#boss-fight"),
  goblinFight: document.querySelector("#boss-fight2"),
  nameEr: document.querySelector("#nameify"),
  gender: document.querySelector("#gender-el"),
  goldPage: document.querySelector("#gold-el"),
  experience: document.querySelector("#xp-el"),
  takeDamage: document.querySelector("#health-bar"),
  enemyBar: document.querySelector("#enemy-bar"),
  enemyPlace: document.querySelector("#enemy-img"),
  instantKill: document.querySelector("#instant-kill"),
  godMode: document.querySelector("#godmode"),
};
